name: nepaltravel
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/logo.png
    - lib/assets/apple.png
    - lib/assets/google.png
    - lib/assets/facebook.png
    - lib/assets/illustration.png
    - lib/assets/illustration.gif
    - lib/assets/social-otr-verification-while-logging-into-account.gif

  # Uncomment and configure the fonts section if you have custom fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# flutter_launcher_icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons.png"
